name: CD - Deploy to Minikube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t local/my-app .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy.yaml
          kubectl get all

      - name: Test app
        run: |
          kubectl port-forward service/my-app 8080:8080 &
          sleep 5
          curl -i http://localhost:8080/